### ISSUE TITLE
Error handling broken

### ISSUE THREAD

**Issue by aenario** [cozy/americano#28]
With express 4.4, the errorhandler middleware should be placed after the routes functions app.get, app.put, ....

The only way to do it with current version of americano is to place it in afterStart : 
https://github.com/aenario/cozy-emails/blob/b5235e503247e5c95f6be9a7fc9c45f3dd2e4274/server/config.coffee#L23

So the default config will use express simpler error handler, which doesn't support outputting the error as JSON.

We could either add a `useAfter` config option or just always include it.

**Comment by frankrousseau** [comment]
Express looks to handle automatically errors when you use next error. 
Whatever, I'm looking for adding a useAfter option to the config.

**Comment by frankrousseau** [comment]
What I read in [documentation](http://expressjs.com/guide/error-handling.html) is:

    Though not strictly required, by convention you define error-handling middleware last, after other app.use() calls;

There is nothing mentioning that it should be set after routes. Could you give me more details?

**Comment by aenario** [comment]
I made one of the fix in another page of the same site in october : https://github.com/strongloop/expressjs.com/commit/a39eccb4e79144c4d4b9f039f31ece9aa04a5b4b

Since then, another contributor has added (in the same page) :
"load errorHandler after loading the app routes"

I just opened a PR to fix the page you mentionned : https://github.com/strongloop/expressjs.com/pull/329

Express by itself do handle errors, however it display them as html /plaintext always. Whereas the americano.errorHandler respond with a JSON object if the request has the "Accept: application/json" header. This hels to propagate the error cleanly to the client. (Instead of the usual "Cant parse JSON : Unexpected Token N" for a "Not Found" error)

**Comment by frankrousseau** [comment]
Ok I understand better. I added the useAfter field but I didn't succed in making it working. I wanted to be sure it's really useful.

**Comment by frankrousseau** [comment]
Cool, mine is still waiting after 3 months. Once done, we'll have 3 contributions to Express!

**Comment by frankrousseau** [comment]
I'm probably missing something but I can't configure an error handler anymore with Express. Wherever I put it before or after the route configuration, the error handler is not runned by Express.

**Comment by frankrousseau** [comment]
OK With a non Americano Express server, I made it works.

**Comment by frankrousseau** [comment]
I think it's fixed. I published a 0.4.0 version. Let me know if it works for you.

**Comment by aenario** [comment]
Ok.

I will test it in email during this sprint.

**Comment by frankrousseau** [comment]
I didn't make a PR. Feel free to review the code.

**Comment by frankrousseau** [comment]
I don't have any news from you about this bug. I close the issue. Feel free to reopen it if needed.
