### ISSUE TITLE
Cannot set env value

### ISSUE THREAD

**Issue by r3dlin3** [cozy/americano#33]
Hi,

I cannot set a value in process.env through the configuration (config.js file).
I have tried different things but when I try  `console.log("DEBUG="+process.env.DEBUG);`, I still get `undefined`
Note: I'm trying to set `DEBUG` for printit.
Note: I have upgraded to version 0.4.2.

So far, what I have tried:
```javascript
var config = {
    common: {
        use: [
            americano.bodyParser(),
            americano.methodOverride(),
            americano.errorHandler({dumpExceptions: true, showStack: true}),
            americano.static(__dirname + '/../client/public', {maxAge: 86400000}),
            americano.set('DEBUG', true)   // get an error "has no method 'set'"

        ],
        set: {
            debug:true,
            DEBUG:true
        }


    },
    development: {
        use: [
            americano.logger('dev')
        ],
        set: {
            debug:true,
            DEBUG:true
        }

    },
```

**Comment by clochix** [comment]
@aenario could you answer @r3dlin3 ? Thanks !

**Comment by frankrousseau** [comment]
Environment variable must be set via the command line or programatically via `process.env`. Americano only handles the `env` function of ExpressJS. So you can't set the DEBUG environment variable through Americano.

**Comment by r3dlin3** [comment]
Sorry for this noob question :p
