### ISSUE TITLE
middlewares stopped being bundled with Express

### ISSUE THREAD

**Issue by maxlath** [cozy/americano#34]
creating a project with `americano myproject` builds a project with middleware errors due to the changes in Express:

```
Error: Most middleware (like urlencoded) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
```

```
Error: Most middleware (like json) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
```

commenting-out `americano.json()` and `americano.urlencoded()` in the config file stops the errors.

**Comment by clochix** [comment]
Thanks for reporting @maxlath, we'll try to fix this soon :-)

**Comment by bnjbvr** [comment]
Saw that locally here as well.

**Comment by maxlath** [comment]
you're welcome!
If you do need them, both middlewares seem to have been moved to [body-parser](https://github.com/expressjs/body-parser)'s repo
