### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by aenario** [cozy/americano#35]
We should allow americano to power an https server by passing an https options object in the config file and starting a http or https server depending on this option.

See : 
http://expressjs.com/en/api.html#app.listen
https://github.com/cozy/americano/blob/134f4831af9a877948554ae84c7bbe2d5552b4d1/main.coffee#L209

**Comment by nono** [comment]
Fixed with 79adc646ebc8d63d892725df3f6f7b77af2478ab
